web/router.ex
defmodule SampleApp.Router do
  use SampleApp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # - get: HTTP メソッド (HTTP Method)
  # - "/home": パス (Path)
  # - StaticPagesController: コントローラ名 (Controller name)
  # - :home: アクション名 (Action name)

  # デモアプリの時は以下の様な感じになっていた
  # - resources: HTTP メソッド
  # - "users": パス
  # - UserController: コントローラ
  # - アクション部分: RESTful のアクション全部
  scope "/", SampleApp do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/home", StaticPagesController, :home
    get "/help", StaticPagesController, :help
    get "/about", StaticPagesController, :about
    get "/contact", StaticPagesController, :contact
    # サインアップルーティング追加
    get "/signup", UserController, :new
    resources "/user", UserController, except: [:new]
    get "/signin", SessionController, :new
    post "/session", SessionController, :create
    delete "/signout", SessionController, :delete
    resources "/post", MicropostController, only: [:create, :delete]
    get "user/:id/following", UserController, :following
    get "user/:id/followers", UserController, :followers
    resources "/relationship", RelationshipController, only: [:create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", SampleApp do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule SampleApp.LayoutView do
  use SampleApp.Web, :view

  # デバッグ情報としてコントローラー名とアクション名を表示する関数
  def get_controller_name(conn), do: controller_module(conn)
  def get_action_name(conn), do: action_name(conn)
end

web/templates/layout/app.html.eex
<!DOCTYPE html><html lang="en"><head>  <meta charset="utf-8">  <meta http-equiv="X-UA-Compatible" content="IE=edge">  <meta name="viewport" content="width=device-width, initial-scale=1">  <meta name="description" content="">  <meta name="author" content="">  <title>Sample App!!</title>    <link rel="stylesheet"    href="<%= static_path(@conn, "/css/app.css") %>">  <link rel="stylesheet"    href="<%= static_path(@conn, "/css/bootstrap.css") %>">  <link rel="stylesheet"    href="<%= static_path(@conn, "/css/custom.css") %>">  <!-- render別テンプレートを呼び出し -->  <%= render "shim.html" %></head><body>  <%= render "header.html", conn: @conn %>  <div class="container">    <h2>      <!-- フラッシュメッセージの表示 -->      <p class="alert alert-info" role="alert"        style="text-align: center;"><%= get_flash(@conn, :info) %>      </p>      <p class="alert alert-danger" role="alert"        style="text-align: center;"><%= get_flash(@conn, :error) %>      </p>    </h2>    <%= render @view_module, @view_template, assigns %>    <%= render "footer.html", conn: @conn %>  </div>  <div class="container">    <%= render "debug.html", conn: @conn %>  </div>  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>  <script src="<%= static_path(@conn, "/js/bootstrap.js") %>"></script></body></html>

web/templates/layout/debug.html.eex
<div class="debug_dump">
  <p>Controller: <%= get_controller_name @conn %></p>
  <p>Action: <%= get_action_name @conn %></p>
  <!-- サインイン中かどうかで処理を切り替え -->
  <%= if current_user(@conn) do %>
    <p>User (ID): <%= current_user(@conn).name %>
  <% end %>
</div>

web/templates/layout/footer.html.eex
<footer class="footer">
  <nav>
    <ul>
      <li><%= link "About", to: static_pages_path(@conn, :about) %></li>
      <li><%= link "Contact", to: static_pages_path(@conn, :contact) %></li>
      <li><a href="http://www.phoenixframework.org/docs">
        Phoenix Get Started
      </a>
    </li>
  </ul>
</nav>
</footer>

web/templates/layout/header.html.eex
<header class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="logo" href="<%= page_path(@conn, :index) %>"></a>
      <nav>
        <ul class="nav nav-pills pull-right">
          <li><%= link "Home", to: static_pages_path(@conn, :home) %></li>
          <%= if current_user(@conn) do %>
          <li class="dropdown">
            <!-- Dropdown Menu -->
            <a href="#" class="dropdown-toggle"
              id="account" data-toggle="dropdown">User Menu<span class="caret"></span>
            </a>
            <!-- Dropdown List -->
            <ul class="dropdown-menu" aria-labelledby="account">
              <li>
                <%= link "All Users", to: user_path(@conn, :index) %>
              <li>
              <li>
                <%= link "Profile",
                  to: user_path(@conn, :show, current_user(@conn)) %>
              </li>
              <li>
                <%= link "Help", to: static_pages_path(@conn, :help) %>
              </li>
              <li class="divider"></li>
              <li class="dropdown-delete-li">
                <%= link "Sign-out", to: session_path(@conn, :delete),
                  method: :delete, class: "dropdown-delete-link" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link "Sign-in", to: session_path(@conn, :new) %></li>
          <% end %>
          </ul>
        </nav>
      </div> <!-- container -->
    </div> <!-- navbar-inner -->
</header>

web/templates/layout/shim.html.eex
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
</script>
<![endif]-->